# -*- coding: utf-8 -*-
"""Untitled36.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cf3K74_RYxcV58bkZ96x6TzXv2uJcav3
"""

import streamlit as st
import pandas as pd
import hashlib
import datetime
from dataclasses import dataclass

@dataclass
class PensionRecord:
    year: int
    salary: float
    accrual_rate: float  # e.g., 1/49 = 0.0204
    cpi_index: float     # Inflation adjustment for that year

    def calculate_unit(self):
        return (self.salary * self.accrual_rate) * (1 + self.cpi_index)

@dataclass
class Block:
    index: int
    record: PensionRecord
    prev_hash: str
    timestamp: str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    def hash_block(self):
        block_string = f"{self.index}{self.record}{self.prev_hash}{self.timestamp}"
        return hashlib.sha256(block_string.encode()).hexdigest()

# Streamlit App
st.set_page_config(page_title="CARE Blockchain Pension", layout="wide")
st.title("🛡️ CARE Pension Blockchain")
st.markdown("Each block represents one year of pensionable service.")

if "chain" not in st.session_state:
    # Initialize with a Genesis Block
    genesis_record = PensionRecord(2023, 0, 0, 0)
    st.session_state.chain = [Block(0, genesis_record, "0")]

# Sidebar: Input for the current year
with st.sidebar:
    st.header("Add Financial Year")
    year = st.number_input("Year", value=2024)
    salary = st.number_input("Annual Salary (£)", min_value=0.0, step=1000.0)
    accrual_denom = st.selectbox("Accrual Rate (1/x)", [49, 57, 60], index=0)
    cpi = st.slider("Inflation Revaluation (CPI %)", -2.0, 10.0, 2.0) / 100

    if st.button("Secure Year in Blockchain"):
        accrual_rate = 1 / accrual_denom
        new_record = PensionRecord(year, salary, accrual_rate, cpi)
        prev_hash = st.session_state.chain[-1].hash_block()
        new_block = Block(len(st.session_state.chain), new_record, prev_hash)
        st.session_state.chain.append(new_block)
        st.success(f"Year {year} locked!")

# Display Data
df_data = []
total_pension = 0

for block in st.session_state.chain[1:]: # Skip Genesis
    unit = block.record.calculate_unit()
    total_pension += unit
    df_data.append({
        "Year": block.record.year,
        "Salary": f"£{block.record.salary:,.2f}",
        "Accrual": f"1/{int(1/block.record.accrual_rate)}",
        "Inflation": f"{block.record.cpi_index:.1%}",
        "Pension Earned": f"£{unit:,.2f}",
        "Block Hash": block.hash_block()[:15] + "..."
    })

if df_data:
    st.table(pd.DataFrame(df_data))

    # Financial Summary
    col1, col2 = st.columns(2)
    col1.metric("Total Annual Pension Pot", f"£{total_pension:,.2f}")
    col2.metric("Blocks (Years) Verified", len(st.session_state.chain) - 1)
else:
    st.info("No years logged yet. Use the sidebar to add your first year of earnings.")